name: User Service CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

      # 1. GitHub repository ka code runner mein checkout hoga
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Node.js setup
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 3. Dependencies install
      - name: Install dependencies
        run: npm ci

      # 4. GitHub OIDC token ke claims check karenge
      - name: Debug OIDC Token
        uses: github/actions-oidc-debugger@main

      # 5. AWS authentication
      # TEMPORARILY COMMENTED.
      # OIDC sub claim milne ke baad isko wapas enable karenge.

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      #     aws-region: eu-north-1

      # 6. ECR login
      # TEMPORARILY COMMENTED

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v2

      # 7. Docker image build
      # TEMPORARILY COMMENTED

      # - name: Build Docker image
      #   run: |
      #     docker build -t user-service:${{ github.sha }} .

      # 8. Docker image ko ECR ke naam se tag karenge
      # TEMPORARILY COMMENTED

      # - name: Tag Docker image
      #   run: |
      #     docker tag \
      #       user-service:${{ github.sha }} \
      #       ${{ steps.login-ecr.outputs.registry }}/user-service:${{ github.sha }}

      # 9. ECR mein Docker image push karenge
      # TEMPORARILY COMMENTED

      # - name: Push Docker image to ECR
      #   run: |
      #     docker push \
      #       ${{ steps.login-ecr.outputs.registry }}/user-service:${{ github.sha }}